#!/usr/bin/env node
/*
 * Generates web/public/_headers with a strict, hash-based CSP.
 *
 * The app is one HTML file with a single inline <script> and <style>. Their
 * sha256 hashes change on every edit, so the CSP is generated from the file
 * rather than hand-maintained. Run `npm run build` after editing index.html;
 * `npm run scan` fails if _headers is stale.
 *
 * Pass --check to verify without writing (used by CI and the pre-commit hook).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const HTML = join(root, 'web/public/index.html');
const HEADERS = join(root, 'web/public/_headers');

/* Origins the page is allowed to reach.
 *
 * Two of them, on purpose and only for now. The Worker is moving from its
 * workers.dev hostname to api.musetteapp.com, and phones carry the old URL in
 * localStorage (v2.cfg), so a copy of the app that has not been reopened yet is
 * still talking to the old host. Naming both means the move does not depend on
 * every phone updating in the same hour.
 *
 * Drop the workers.dev entry once no phone is using it - it is the last thing
 * keeping a *.workers.dev origin in the policy, and leaving it is exactly the
 * kind of "temporary" that becomes permanent. */
const SYNC_ORIGINS = [
  'https://api.musetteapp.com',
  'https://shopping-list-sync.markpjacobs1.workers.dev', // TODO: remove after the cutover
];

const sha256 = (s) => `'sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}'`;

/* Collect the text content of every inline <script>/<style> (no src/href). */
function inlineHashes(html, tag) {
  const re = new RegExp(`<${tag}([^>]*)>([\\s\\S]*?)</${tag}>`, 'gi');
  const out = [];
  for (const m of html.matchAll(re)) {
    if (/\b(src|href)=/i.test(m[1])) continue;
    out.push(sha256(m[2]));
  }
  return out;
}

const html = readFileSync(HTML, 'utf8');
const scripts = inlineHashes(html, 'script');
const styles = inlineHashes(html, 'style');

if (!scripts.length) {
  console.error('build-csp: no inline <script> found - refusing to emit a CSP that blocks the app');
  process.exit(1);
}

const csp = [
  "default-src 'none'",
  `script-src ${scripts.join(' ')}`,
  `style-src ${styles.join(' ') || "'none'"}`,
  'img-src data:',
  `connect-src ${SYNC_ORIGINS.join(' ')}`,
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join('; ');

const body = `# GENERATED by tools/build-csp.mjs - do not edit by hand.
# Re-run \`npm run build\` after changing index.html, or the script hash goes stale
# and the browser will refuse to execute the app.
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  X-Frame-Options: DENY
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
`;

const check = process.argv.includes('--check');

if (check) {
  if (!existsSync(HEADERS)) {
    console.error('build-csp --check: web/public/_headers is missing. Run `npm run build`.');
    process.exit(1);
  }
  if (readFileSync(HEADERS, 'utf8') !== body) {
    console.error(
      'build-csp --check: _headers is STALE - the CSP hash does not match index.html.\n' +
        'The deployed app would be blocked by its own CSP. Run `npm run build`.'
    );
    process.exit(1);
  }
  console.log(`build-csp --check: ok (script ${scripts[0]})`);
} else {
  writeFileSync(HEADERS, body);
  console.log(`build-csp: wrote _headers`);
  console.log(`  script-src ${scripts.join(' ')}`);
  console.log(`  style-src  ${styles.join(' ')}`);
  console.log(`  connect-src ${SYNC_ORIGINS.join(' ')}`);
}
